package throwing.custom.exception.manually;

public class Test {

	public static void main(String[] args) {
		
		

	}

}
